repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
  - repo: https://github.com/prettier/prettier
    rev: 2.5.0
    hooks:
      - id: prettier
        args: [--write, './**/*.ts', './**/*.tsx']
  - repo: https://github.com/reviewdog/action-eslint
    rev: master

    hooks:
      - id: eslint
        args: [--fix]
