repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files

    - repo: https://github.com/prettier/prettier
      rev: '2.5.1'
      hooks:
          - id: prettier
            args: ['--write', '.']
            name: prettier
            types: [javascript, json, css, scss, less, jsx, tsx, html, yaml]

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v7.8.1'
      hooks:
          - id: eslint
            name: eslint
            entry: npx eslint
            language: node
            types: [javascript, jsx, tsx]
