repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: ''
      hooks:
          - id: eslint
            files: \.[jt]sx?$
            types: [file]
